print("-------------------")
print("Enter first no:")
num1 = input()
print ("Enter second no:")
num2 = input()
print("----------")
print("first no: {}".format(num1))
print("second no:{}".format(num2))
print("------------------------------")
